### ISSUE TITLE
Cenário C terá dificuldade.

### ISSUE THREAD

**Issue by eduardomarossi** [gabrielvf1/VisorMaquinadeLavar#11]
Muita informação numa única tela, as setas podiam ser coloridas para chamar atenção (elas são relativamente pequenas do tamanho da tela).

A senhora poderá ter bastante dificuldade em selecionar o ciclo.

O botão "Power" poderia estar escrito Ligar quando estiver desligado. Uma senhora pode ter dificuldade de reconhecer o botão Power ou conhecer.

**Comment by gabrielvf1** [comment]
Conversei com o Rafa ele disse que esta tudo ok com esse issue
