### ISSUE TITLE
Include após definir váriaveis globais, é altamente recomendável os includes vir primeiro e separar por seções

### ISSUE THREAD

**Issue by eduardomarossi** [gabrielvf1/VisorMaquinadeLavar#2]
https://github.com/gabrielvf1/VisorMaquinadeLavar/blob/68311c2f91555074468347e720947f6871dbf5d7/MXT_EXAMPLE_USART1/src/main.c#L131-L165

**Comment by gabrielvf1** [comment]
100% de razao, mudanca alterada.
