### ISSUE TITLE
Variáveis globais como vel_string, distancia_string não são utilizadas

### ISSUE THREAD

**Issue by eduardomarossi** [gabrielvf1/VisorMaquinadeLavar#4]
https://github.com/gabrielvf1/VisorMaquinadeLavar/blob/68311c2f91555074468347e720947f6871dbf5d7/MXT_EXAMPLE_USART1/src/main.c#L148

**Comment by gabrielvf1** [comment]
Realmente as variveis nao estavam sendo utilizadas, foram retiradas.
