### ISSUE TITLE
Número mágico do status do touch, poderia ter sido feito um define para tentar descrever o que quer dizer

### ISSUE THREAD

**Issue by eduardomarossi** [gabrielvf1/VisorMaquinadeLavar#8]
https://github.com/gabrielvf1/VisorMaquinadeLavar/blob/68311c2f91555074468347e720947f6871dbf5d7/MXT_EXAMPLE_USART1/src/main.c#L527

**Comment by gabrielvf1** [comment]
Correção realizada defines feitos
