### ISSUE TITLE
Poderia ter utilizado formatação do sprintf para inserir duas casas decimais e fazer de uma vez direto

### ISSUE THREAD

**Issue by eduardomarossi** [gabrielvf1/VisorMaquinadeLavar#9]
https://github.com/gabrielvf1/VisorMaquinadeLavar/blob/68311c2f91555074468347e720947f6871dbf5d7/MXT_EXAMPLE_USART1/src/main.c#L493-L510

Supondo que horas = 01, minutos = 00, segundos = 20
Poderia se exibir 01:00:20
`
sprintf("%02d:%02d:%02d", horas, minutos, segundos);
`

Fica mais fácil de entender do que 1:0:20 e ao mesmo tempo não precisa se preocupar com as coordenadas/desenho de cada parte.

**Comment by gabrielvf1** [comment]
Sim tem razão nao sabia ainda direito utilizar o sprintf. Otima dica
